### ISSUE TITLE
waveform~

### ISSUE THREAD

**Issue by randallpacker** [composingcap/grainflow#13]
Chris I wanted to let you know that you seemed to have fixed jsui waveform~ with the latest release, it's no longer crashing. Bravo! 

It is still a little buggy though, for example, sometimes when I copy a patch, the waveform~ becomes transparent and doesn't respond to color changes. However if I just a new object it's fine. 

I am using grainflow~ extensively in a project and appreciate the great work you are doing to refine it. 

Best. Randall

**Comment by composingcap** [comment]
I am having trouble reproducing this issue.  Could you upload an example of a patch that does this?

**Comment by randallpacker** [comment]
I can't seem to reproduce it myself any longer. I wonder if your update from yesterday has resolved it.

**Comment by composingcap** [comment]
I am going to mark this as resolved.  Feel free to open it up again if crashes occur again
