### ISSUE TITLE
Maybe older version of Grainflow needs to be uninstalled before installing v1.0

### ISSUE THREAD

**Issue by theejimpee** [composingcap/grainflow#16]

**Comment by theejimpee** [comment]
Sorry - submitted that before typing more...

I just found a potential (minor) issue:  I used Max (8.3.1) package manager to update Grainflow from 0.3.something to the newest 1.0.0 - then restarted Max.

when i tried to load up either the grainflow.streams~ help page or the "Streams" tab in  the grainflow~ overfview patch, the Console printed multiple errors along the lines of "gen can't understand stream" and "gen can't understand streamSet".  Plus the patch didn't seem to be operating as I now see it does.

Sorry that's not much detail on the errors, i didn't spend much time looking at them - I just used package manager to uninstall then reinstall grainflow then restart Max.  Now it looks to be working as intended.

Not sure if this just affected me, or whether it's simply best practice to uninstall a package before installing an upgrade?  Or perhaps you might want to recommend other users uninstall previous version before upgrading?  anyway all the best , thanks for the wonderful work!

**Comment by composingcap** [comment]
Thanks for the report. I am not sure what is happening exactly, but I would guess the gen~ code was accessing an older version somehow and a fresh install on my secondary machine seems fine and I tried changing versions as well which seemed to work on my machine... My guess is something in the package manager went wrong where it updated- perhaps a file was in use and it could not be overwritten?

**Comment by composingcap** [comment]
I am going to mark this as resolved but please re-open it if the issue presents again.
