### ISSUE TITLE
What is the .maxpack file format?

### ISSUE THREAD

**Issue by shakfu** [composingcap/grainflow#23]
In your recent releases, you release a single .maxpack file. I've never seen this kind of file before in the context of Max. What does one do with such files?

**Comment by composingcap** [comment]
Hey Shakeeb,

The Maxpack is actually a masquerading .zip archive. I just learned about
these as well, but Max will automatically install them into your packages
folder if you open it with Max which is pretty convenient.

**Comment by shakfu** [comment]
Cool. Thanks for the explanation, Chris.

**Comment by shakfu** [comment]
@composingcap I think you should probably add a note to your release to indicate what is to be done with .maxpack format as it is probably not self-evident.
